/* ============================================================
   LANG FR — Cabinet MHBM Avocats-Conseils
   Version Production — Juin 2025
   ============================================================ */
window.LANG_FR = {
  /* ── Méta & SEO ── */
  meta_title: "Avocat Tunisie en ligne | Cabinet MHBM — Maître Ben Makhlouf",
  meta_desc: "Cabinet MHBM Avocat, fondé par Maître Mohamed Haithem Ben Makhlouf, avocat près de la Cour de Cassation. Conseil juridique en Tunisie et consultation en ligne pour les Tunisiens du monde entier.",

  /* ── Topbar ── */
  topbar_msg: "Vous vivez à l'étranger ? Consultez un avocat tunisien en ligne — Réponse sous 24h",
  topbar_cta: "Prendre rendez-vous →",

  /* ── Navigation ── */
  nav_home: "Accueil",
  nav_cabinet: "Le Cabinet",
  nav_presentation: "Présentation",
  nav_equipe: "L'Équipe",
  nav_valeurs: "Nos Valeurs",
  nav_bureaux: "Nos Bureaux",
  nav_expertises: "Expertises",
  nav_exp_succession: "Droit Successoral",
  nav_exp_immobilier: "Droit Immobilier",
  nav_exp_divorce: "Divorce International",
  nav_exp_affaires: "Droit des Affaires",
  nav_exp_penal: "Droit Pénal",
  nav_exp_nationalite: "Nationalité Tunisienne",
  nav_exp_arbitrage: "Arbitrage & Médiation",
  nav_exp_recouvrement: "Recouvrement",
  nav_exp_travail: "Droit du Travail",
  nav_exp_famille: "Droit de la Famille",
  nav_exp_accidents: "Accidents & Indemnisation",
  nav_exp_baux: "Baux & Litiges",
  nav_etranger: "Tunisiens à l'Étranger",
  nav_consultation: "Consultation",
  nav_ressources: "Ressources",
  nav_blog: "Blog & Articles",
  nav_guides: "Guides Pratiques",
  nav_faq: "FAQ",
  nav_honoraires: "Honoraires",
  nav_contact: "Contact",
  nav_espace_client: "Espace Client",
  nav_rdv: "Prendre RDV",
  nav_whatsapp: "💬 WhatsApp",

  /* ── Hero ── */
  hero_tagline: "Avocat près de la Cour de Cassation · Barreau de Tunisie",
  hero_title_1: "Votre avocat en Tunisie —",
  hero_title_2: "disponible où que vous",
  hero_title_3: "soyez dans le monde",
  hero_subtitle: "Depuis M'saken, Maître Mohamed Haithem Ben Makhlouf et son équipe défendent vos droits, sécurisent vos intérêts et vous accompagnent dans chaque démarche juridique — en Tunisie et depuis l'étranger.",
  hero_sub2: "Que vous soyez à Paris, Montréal, Bruxelles ou Dubaï, vos droits en Tunisie ne s'arrêtent pas à la frontière.",
  hero_exp_badge: "Plus de 18 ans d'expérience. Plus de 5 000 dossiers traités.",
  hero_cta_rdv: "📅 Réserver une consultation",
  hero_cta_wa: "💬 WhatsApp",
  hero_badge_1: "Réponse sous 24h ouvrées",
  hero_badge_2: "Confidentialité absolue",
  hero_badge_3: "Honoraires transparents",

  /* ── Stats ── */
  stat_years: "+18",
  stat_years_label: "années d'exercice",
  stat_years_sub: "Depuis 2007",
  stat_cases: "+5 000",
  stat_cases_label: "dossiers traités",
  stat_cases_sub: "Tous domaines confondus",
  stat_team: "3",
  stat_team_label: "avocats & juristes",
  stat_team_sub: "Une équipe soudée",
  stat_conf: "100%",
  stat_conf_label: "confidentialité",
  stat_conf_sub: "Secret professionnel garanti",

  /* ── À propos ── */
  about_eyebrow: "Le Cabinet",
  about_title: "Un cabinet construit sur la confiance, l'expertise et l'engagement",
  about_p1: "Cabinet MHBM Avocat a été fondé en 2010 par Maître Mohamed Haithem Ben Makhlouf, avocat près de la Cour de Cassation, après plusieurs années d'exercice et une formation académique d'excellence.",
  about_p2: "Ce qui distingue Cabinet MHBM Avocat, c'est une approche résolument moderne de la profession : écoute active, conseil stratégique en amont des litiges, suivi personnalisé de chaque dossier.",
  about_p3: "Notre clientèle est aussi bien locale qu'internationale. Nous accompagnons quotidiennement des Tunisiens résidant en France, Belgique, Allemagne, Canada, Italie et dans les pays du Golfe.",
  about_link: "→ Découvrir notre histoire complète",
  about_feat_1: "Secret professionnel absolu",
  about_feat_2: "Consultations 100% en ligne",
  about_feat_3: "Disponible du lundi au samedi",
  about_feat_4: "Honoraires transparents",
  about_feat_5: "Avocat près de la Cour de Cassation",

  /* ── Expertises ── */
  exp_eyebrow: "Expertises",
  exp_title: "Nos domaines d'expertise",
  exp_subtitle: "Une couverture juridique complète pour particuliers, familles, entrepreneurs et investisseurs",
  exp_more: "En savoir plus",
  exp_all: "→ Voir toutes nos expertises",

  exp_succession_title: "Droit Successoral & Héritage",
  exp_succession_desc: "Succession ouverte en Tunisie, partage entre héritiers, liquidation de patrimoine — nous gérons chaque étape avec rigueur.",
  exp_immobilier_title: "Droit Immobilier",
  exp_immobilier_desc: "Acquisition, vente, litige locatif, copropriété — sécurisez chaque transaction immobilière avec un expert du droit tunisien.",
  exp_divorce_title: "Divorce International",
  exp_divorce_desc: "Divorce entre époux résidant dans des pays différents, garde d'enfants, pension alimentaire — accompagnement humain et juridique.",
  exp_affaires_title: "Droit des Affaires",
  exp_affaires_desc: "Création de sociétés, contrats commerciaux, litiges entre associés, recouvrement — protégez votre activité.",
  exp_penal_title: "Droit Pénal",
  exp_penal_desc: "Défense pénale, assistance en garde à vue, représentation devant les tribunaux correctionnels et criminels tunisiens.",
  exp_nationalite_title: "Nationalité Tunisienne",
  exp_nationalite_desc: "Acquisition, récupération ou confirmation de la nationalité tunisienne — démarches simplifiées pour les Tunisiens de l'étranger.",
  exp_arbitrage_title: "Arbitrage & Médiation",
  exp_arbitrage_desc: "Résolution amiable ou arbitrale des conflits commerciaux — alternative rapide et confidentielle aux procédures judiciaires.",
  exp_recouvrement_title: "Recouvrement de Créances",
  exp_recouvrement_desc: "Recouvrement amiable et judiciaire, injonctions de payer, saisies — récupérez ce qui vous est légalement dû.",
  exp_travail_title: "Droit du Travail",
  exp_travail_desc: "Licenciements abusifs, conflits employeur-salarié, contrats de travail, droit syndical — défense de vos droits sociaux.",
  exp_famille_title: "Droit de la Famille",
  exp_famille_desc: "Mariage, divorce, garde d'enfants, adoption, pensions alimentaires — accompagnement sensible dans chaque situation familiale.",
  exp_accidents_title: "Accidents & Indemnisation",
  exp_accidents_desc: "Accidents de la route, responsabilité civile, indemnisation des victimes — nous défendons vos droits face aux assurances.",
  exp_baux_title: "Baux & Litiges Immobiliers",
  exp_baux_desc: "Baux d'habitation, baux commerciaux, expulsion, troubles de voisinage, copropriété — sécurisez vos relations locatives.",

  /* ── Étranger ── */
  etranger_eyebrow: "Tunisiens à l'Étranger",
  etranger_title: "Vous vivez à l'étranger. Vos droits en Tunisie nous concernent.",
  etranger_p1: "Gérer un héritage en Tunisie depuis Paris. Acheter un appartement à Sousse depuis Montréal. Établir une procuration depuis Bruxelles. Ces situations, nos clients les vivent chaque jour — et nous les résolvons chaque jour.",
  etranger_p2: "Cabinet MHBM Avocat a développé une expertise spécifique pour les Tunisiens non-résidents. Nous connaissons vos contraintes : les décalages horaires, l'impossibilité de vous déplacer, la complexité des démarches transfrontalières.",
  etranger_p3: "Nous intervenons à chaque étape, en langue française, avec une communication claire, régulière et transparente. Consultation vidéo, WhatsApp, email, espace client sécurisé.",
  etranger_cta: "→ Je consulte un avocat en ligne maintenant",
  etranger_note: "Première prise de contact gratuite · Réponse sous 24h",
  etranger_guide_heritage: "🏛️ Héritage → Guide complet",
  etranger_guide_immo: "🏠 Immobilier → Guide complet",
  etranger_guide_procu: "📄 Procurations → Guide complet",
  etranger_guide_invest: "📈 Investissement → Guide complet",
  etranger_guide_exec: "⚖️ Exécution de jugements → Guide complet",

  /* ── Consultation ── */
  consult_eyebrow: "Consultation en Ligne",
  consult_title: "Consultez notre cabinet. Depuis n'importe où.",
  consult_subtitle: "Trois modes de consultation adaptés à votre situation et à votre emploi du temps",
  consult_video_title: "Rendez-vous vidéo",
  consult_video_desc: "Un entretien confidentiel avec Maître Ben Makhlouf via Zoom ou Google Meet. Vous exposez votre situation, nous analysons, nous conseillons.",
  consult_video_meta: "45 minutes · Sur rendez-vous",
  consult_video_cta: "Réserver un créneau →",
  consult_video_badge: "Recommandé",
  consult_wa_title: "Consultation WhatsApp",
  consult_wa_desc: "Posez votre question directement à notre équipe. Idéal pour une première orientation ou un suivi rapide de dossier.",
  consult_wa_meta: "Réponse sous 24h ouvrées",
  consult_wa_cta: "Écrire maintenant →",
  consult_avis_title: "Avis juridique écrit",
  consult_avis_desc: "Recevez un avis juridique détaillé et documenté, rédigé par notre cabinet, livré en PDF sous 48 à 72 heures ouvrées.",
  consult_avis_meta: "PDF signé · Français et Arabe",
  consult_avis_cta: "Demander un avis →",

  /* ── Témoignages ── */
  testi_eyebrow: "Témoignages",
  testi_title: "Ce que nos clients disent de nous",
  testi_subtitle: "Des milliers de dossiers résolus. Des centaines de familles rassurées.",
  testi_note: "Témoignages recueillis avec l'accord des clients. Identités complètes disponibles sur demande.",

  /* ── Portrait fondateur ── */
  portrait_eyebrow: "Le Fondateur",
  portrait_role: "Fondateur & Avocat Principal",
  portrait_name: "Maître Mohamed Haithem Ben Makhlouf",
  portrait_title_line: "Avocat près de la Cour de Cassation — Fondateur du Cabinet MHBM Avocat",
  portrait_bio: "Titulaire d'une Maîtrise en Droit obtenue en 2004 et d'un DEA de 3ème cycle en 2006, Maître Mohamed Haithem Ben Makhlouf est en exercice depuis 2007. En 2010, il fonde Cabinet MHBM Avocat avec une vision claire : offrir à chaque client un accompagnement juridique de haut niveau, accessible, humain et orienté résultats.",
  portrait_bio2: "Avec plus de 18 ans d'expérience et plus de 5 000 dossiers traités dans tous les domaines du droit tunisien, il est aujourd'hui l'un des avocats les plus sollicités par les Tunisiens non-résidents.",
  portrait_link: "→ Découvrir le parcours complet",
  portrait_badge: "Avocat près de la Cour de Cassation · Barreau de Tunisie · En exercice depuis 2007",

  /* ── Ressources ── */
  ressources_eyebrow: "Ressources",
  ressources_title: "Ressources juridiques gratuites",
  ressources_subtitle: "Comprenez vos droits avant de nous contacter. Nos articles, guides et FAQ sont là pour vous.",
  ressources_all: "→ Accéder à tous nos articles",
  art1_cat: "Héritage",
  art1_title: "Comment gérer un héritage en Tunisie depuis la France : guide complet 2024",
  art1_desc: "Décès d'un proche en Tunisie, biens immobiliers, comptes bancaires, héritiers dispersés entre plusieurs pays...",
  art1_cta: "Lire l'article →",
  art2_cat: "Immobilier",
  art2_title: "Acheter un bien immobilier en Tunisie en tant que non-résident : tout ce qu'il faut savoir",
  art2_desc: "Restrictions légales, documents requis, risques à éviter et étapes clés pour sécuriser votre acquisition...",
  art2_cta: "Lire l'article →",
  art3_cat: "Consultation en ligne",
  art3_title: "Consulter un avocat tunisien depuis l'étranger : comment ça marche ?",
  art3_desc: "La technologie permet aujourd'hui d'accéder à un conseil juridique de qualité sans quitter votre domicile...",
  art3_cta: "Lire l'article →",

  /* ── CTA Final ── */
  cta_eyebrow: "Contact",
  cta_title: "Votre situation mérite une réponse claire. Parlons-en.",
  cta_subtitle: "Premier contact gratuit · Confidentialité garantie · Réponse sous 24h",
  cta_p1: "Ne laissez pas une situation juridique non résolue peser sur votre quotidien. Que vous ayez une question urgente ou un projet à long terme, notre cabinet est là pour vous écouter, vous conseiller et agir à vos côtés.",
  cta_rdv: "📅 Réserver ma consultation",
  cta_tel: "📞 Nous appeler",
  cta_wa_note: "Ou écrivez-nous sur WhatsApp : +216 98 258 015",
  cta_hours: "Lun–Ven 08h00–17h30 · Sam 08h00–13h30",

  /* ── Formulaire ── */
  form_eyebrow: "Formulaire de contact",
  form_title: "Envoyez-nous votre demande",
  form_subtitle: "Réponse garantie sous 24 heures ouvrées",
  form_name: "Nom et prénom",
  form_email: "Email",
  form_phone: "Téléphone",
  form_type: "Type de demande",
  form_type_default: "Sélectionnez votre demande",
  form_type_1: "Droit successoral / Héritage",
  form_type_2: "Droit immobilier",
  form_type_3: "Divorce international",
  form_type_4: "Droit des affaires",
  form_type_5: "Droit pénal",
  form_type_6: "Procuration",
  form_type_7: "Investissement en Tunisie",
  form_type_8: "Nationalité tunisienne",
  form_type_9: "Droit du travail",
  form_type_10: "Accidents & indemnisation",
  form_type_11: "Baux & litiges",
  form_type_12: "Autre demande",
  form_msg: "Message",
  form_rgpd: "J'accepte que mes données soient utilisées pour traiter ma demande, conformément à la politique de confidentialité du cabinet. Ces données ne seront jamais partagées avec des tiers.",
  form_submit: "Envoyer ma demande →",
  form_success_title: "Votre message a bien été envoyé.",
  form_success_msg: "Notre équipe a bien reçu votre demande et vous contactera dans un délai maximum de 24 heures ouvrées. Pour toute question urgente : WhatsApp +216 98 258 015",
  form_error: "Une erreur est survenue. Veuillez réessayer ou nous contacter directement.",

  /* ── Footer ── */
  footer_tagline: "Cabinet de référence en droit tunisien, fondé en 2010. Expertise, discrétion et engagement pour chaque client.",
  footer_nav_title: "Navigation",
  footer_contact_title: "Contact",
  footer_hours_title: "Horaires",
  footer_address: "Rue des Fleurs, M'saken, Sousse 4070, Tunisie",
  footer_hours_1: "Lundi – Vendredi",
  footer_hours_1_val: "08:00 – 17:30",
  footer_hours_2: "Samedi",
  footer_hours_2_val: "08:00 – 13:30",
  footer_hours_3: "Dimanche",
  footer_hours_3_val: "Fermé",
  footer_hours_note: "Consultations en ligne disponibles en dehors des horaires sur rendez-vous",
  footer_copy: "© 2025 Cabinet MHBM Avocat — Tous droits réservés",
  footer_copy2: "Maître Mohamed Haithem Ben Makhlouf, Avocat près de la Cour de Cassation, inscrit au Barreau de Tunisie",
  footer_legal: "Mentions légales",
  footer_privacy: "Confidentialité",
  footer_cookies: "Cookies",
  footer_disclaimer: "Les informations publiées sur ce site ont un caractère général et informatif. Elles ne constituent pas un avis juridique et ne sauraient se substituer à une consultation individuelle avec un avocat. Toute situation juridique étant unique, nous vous invitons à nous contacter pour un conseil personnalisé.",

  /* ── Cookies ── */
  cookie_msg: "Ce site utilise des cookies pour améliorer votre expérience et analyser notre trafic. En poursuivant votre navigation, vous acceptez notre politique de cookies.",
  cookie_accept: "Accepter tous les cookies",
  cookie_manage: "Gérer mes préférences",

  /* ── Espace Client ── */
  ec_login_title: "Connexion Espace Client",
  ec_login_subtitle: "Accédez à vos dossiers, documents et messages en toute sécurité.",
  ec_login_email: "Adresse email",
  ec_login_pwd: "Mot de passe",
  ec_login_show_pwd: "Afficher le mot de passe",
  ec_login_btn: "Se connecter",
  ec_login_demo: "⚡ Connexion démo (test)",
  ec_login_forgot: "Mot de passe oublié ?",
  ec_login_no_account: "Pas encore de compte ?",
  ec_login_create: "Créer un compte",
  ec_register_title: "Créer un compte",
  ec_register_subtitle: "Accédez à votre espace client personnalisé.",
  ec_register_name: "Nom et prénom",
  ec_register_email: "Adresse email",
  ec_register_phone: "Téléphone (optionnel)",
  ec_register_pwd: "Choisissez un mot de passe",
  ec_register_pwd2: "Confirmer le mot de passe",
  ec_register_btn: "Créer mon compte →",
  ec_register_have_account: "Déjà un compte ?",
  ec_register_login: "Se connecter",
  ec_verify_title: "Vérification",
  ec_verify_subtitle: "Un code à 6 chiffres a été envoyé à votre adresse email.",
  ec_verify_label: "Code de vérification",
  ec_verify_btn: "Vérifier →",
  ec_verify_resend: "Renvoyer le code",
  ec_back: "Retour au site",
  ec_demo_warning: "Mode démonstration — aucune donnée réelle",
  ec_dash_title: "Mon tableau de bord",
  ec_dash_welcome: "Bonjour",
  ec_dossiers_title: "Mes dossiers",
  ec_docs_title: "Mes documents",
  ec_msgs_title: "Mes messages",
  ec_consults_title: "Mes consultations",
  ec_payments_title: "Paiements & factures",
  ec_notifs_title: "Notifications",
  ec_profil_title: "Mon profil",
  ec_settings_title: "Paramètres",
  ec_logout: "Déconnexion",

  /* ── Pages internes génériques ── */
  breadcrumb_home: "Accueil",
  page_cta_rdv: "📅 Prendre rendez-vous",
  page_cta_contact: "Nous contacter",
  page_aside_title: "Besoin d'un avis ?",
  page_aside_desc: "Premier contact gratuit. Réponse sous 24h.",
  page_aside_cta: "Prendre rendez-vous",
  page_aside_tel: "Ou appelez-nous :",

  /* ── Page équipe ── */
  equipe_title: "Une équipe d'experts à votre service",
  equipe_subtitle: "Des professionnels du droit tunisien, engagés pour défendre vos droits en Tunisie et depuis l'étranger.",
  equipe_section_title: "Des professionnels engagés à vos côtés",
  equipe_section_sub: "Notre équipe combine expertise juridique, expérience internationale et engagement humain pour offrir un service d'excellence.",
  member_1_name: "Maître Mohamed Haithem Ben Makhlouf",
  member_1_role: "Fondateur & Avocat Principal",
  member_1_domains: "Droit des affaires, Succession, Droit pénal",
  member_1_bio: "Titulaire d'une Maîtrise en Droit (2004) et d'un DEA de 3ème cycle (2006), fondateur du cabinet en 2010. Avocat près de la Cour de Cassation, plus de 18 ans d'expérience.",
  member_2_name: "Maître Chaima Bhiri",
  member_2_role: "Avocate Associée",
  member_2_domains: "Droit de la famille, Divorce international, Garde d'enfants",
  member_2_bio: "Spécialisée dans les procédures transfrontalières de droit familial et les litiges matrimoniaux internationaux.",
  member_3_name: "Maître Aymen Guezguez",
  member_3_role: "Avocat Senior",
  member_3_domains: "Droit immobilier, Recouvrement, Arbitrage",
  member_3_bio: "Expert en transactions immobilières, recouvrement de créances et modes alternatifs de règlement des conflits.",
  equipe_cta_title: "Votre situation mérite une réponse claire.",

  /* ── Bureaux / Contact ── */
  bureaux_map_title: "Notre localisation",
  bureaux_map_link: "Obtenir l'itinéraire →",
  contact_map_title: "Nous trouver",

  /* ── Page presentation ── */
  pres_title: "Notre Histoire",
  pres_subtitle: "Depuis 2007, au service du droit tunisien",
  pres_fondateur_badge: "Fondateur",

  /* ── Honoraires ── */
  honoraires_title: "Honoraires & Tarifs",
  honoraires_subtitle: "Transparence et clarté dans chaque engagement",
  honoraires_devis: "Sur devis",

  /* ── FAQ ── */
  faq_title: "Foire aux questions",
  faq_subtitle: "Retrouvez les réponses aux questions les plus fréquentes",

  /* ── Blog / Guides ── */
  blog_title: "Blog & Articles juridiques",
  blog_subtitle: "Ressources gratuites pour comprendre vos droits",
  guides_title: "Guides pratiques",
  guides_subtitle: "Démarches étape par étape pour les Tunisiens non-résidents",
};
